language: go

services:
  - docker

go:
  - 1.13.x


before_install:
  - docker build -t platform/rules-engine .

script:
  - go test -v
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - make test
  - make image

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-image ;
    fi
  